// <auto-generated />
namespace AppGestionCahierTexte.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class test : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(test));
        
        string IMigrationMetadata.Id
        {
            get { return "202601051614179_test"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
